### ISSUE TITLE
Dockers connected through Tramsission lose connection and can't access web console.

### ISSUE THREAD

**Issue by ZerkerEOD** [haugene/docker-transmission-openvpn#2334]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

docker run -d --name='Transmission_VPN' --net='bridge' --privileged=true -e TZ="Europe/London" -e HOST_OS="Unraid" -e HOST_HOSTNAME="NASty" -e HOST_CONTAINERNAME="Transmission_VPN" -e 'OPENVPN_USERNAME'='redacted' -e 'OPENVPN_PASSWORD'='redacted' -e 'OPENVPN_CONFIG'='SE Stockholm' -e 'OPENVPN_PROVIDER'='PRIVATEVPN' -e 'LOCAL_NETWORK'='redacted/16' -e 'TRANSMISSION_RPC_USERNAME'='redacted' -e 'TRANSMISSION_RPC_PASSWORD'='redacted' -e 'OPENVPN_OPTS'='--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings' -e 'PUID'='99' -e 'PGID'='100' -e 'TRANSMISSION_DOWNLOAD_DIR'='/data/downloads/complete' -e 'TRANSMISSION_RPC_AUTHENTICATION_REQUIRED'='true' -e 'TRANSMISSION_RATIO_LIMIT_ENABLED'='true' -e 'TRANSMISSION_DOWNLOAD_QUEUE_SIZE'='15' -e 'TRANSMISSION_CACHE_SIZE_MB'='10' -e 'TRANSMISSION_INCOMPLETE_DIR'='/data/downloads/incomplete' -e 'TRANSMISSION_WEB_UI'='combustion' -e 'GLOBAL_APPLY_PERMISSIONS'='false' -e 'WEBPROXY_ENABLED'='false' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:9091]/' -l net.unraid.docker.icon='https://raw.githubusercontent.com/activ/docker-templates/master/activ/images/transmission-icon.png' -p '9091:9091/tcp' -p '7878:7878/tcp' -p '8989:8989/tcp' -p '9117:9117/tcp' -p '8080:8080/tcp' -p '9090:9090/tcp' -p '8686:8686/tcp' -v '/mnt/user/data/torrent/':'/data/downloads/':'rw' -v '/mnt/user/data/torrent/watch/':'/watch':'rw' --cap-add=NET_ADMIN --restart=always --log-opt max-size=50m --log-driver json-file --dns 8.8.8.8 --dns 1.1.1.1 'haugene/transmission-openvpn:3.7.1'

### Current Behavior

Dockers connected through transmission lose connection and require the entire stack to reboot to regain connection.

### Expected Behavior

Proper flow of docker network when tunneling everything.

### How have you tried to solve the problem?

continuously reboot containers as they lose connection. Its multiple different dockers and the only constant is transmission.

### Log output

today at 10:49:00 PMStarting container with revision: 47f32618629b0144f492b9116f77978d4c991712
today at 10:49:00 PMCreating TUN device /dev/net/tun
today at 10:49:00 PMmknod: /dev/net/tun: File exists
today at 10:49:00 PMUsing OpenVPN provider: PRIVATEVPN
today at 10:49:00 PMStarting OpenVPN using config SE Stockholm.ovpn
today at 10:49:00 PMSetting OpenVPN credentials...
today at 10:49:01 PMadding route to local network redacted/16 via 172.17.0.1 dev eth0
today at 10:49:01 PM2022-08-29 04:49:01 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
today at 10:49:01 PM2022-08-29 04:49:01 OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
today at 10:49:01 PM2022-08-29 04:49:01 library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10
today at 10:49:01 PM2022-08-29 04:49:01 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
today at 10:49:01 PM2022-08-29 04:49:01 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
today at 10:49:01 PM2022-08-29 04:49:01 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
today at 10:49:01 PM2022-08-29 04:49:01 TCP/UDP: Preserving recently used remote address: [AF_INET]45.130.87.14:1194
today at 10:49:01 PM2022-08-29 04:49:01 Socket Buffers: R=[212992->212992] S=[212992->212992]
today at 10:49:01 PM2022-08-29 04:49:01 UDP link local: (not bound)
today at 10:49:01 PM2022-08-29 04:49:01 UDP link remote: [AF_INET]45.130.87.14:1194
today at 10:49:01 PM2022-08-29 04:49:01 TLS: Initial packet from [AF_INET]45.130.87.14:1194, sid=c45f221f 69f42df8
today at 10:49:01 PM2022-08-29 04:49:01 VERIFY OK: depth=1, C=SE, ST=CA, L=Stockholm, O=PrivateVPN, CN=PrivateVPN CA, name=PrivateVPN, emailAddress=support@privatvpn.se
today at 10:49:01 PM2022-08-29 04:49:01 VERIFY KU OK
today at 10:49:01 PM2022-08-29 04:49:01 Validating certificate extended key usage
today at 10:49:01 PM2022-08-29 04:49:01 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
today at 10:49:01 PM2022-08-29 04:49:01 VERIFY EKU OK
today at 10:49:01 PM2022-08-29 04:49:01 VERIFY OK: depth=0, C=SE, ST=CA, L=Stockholm, O=PrivateVPN, CN=PrivateVPN, name=PrivateVPN, emailAddress=support@privatvpn.se
today at 10:49:01 PM2022-08-29 04:49:01 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 2048 bit RSA, signature: RSA-SHA256
today at 10:49:01 PM2022-08-29 04:49:01 [PrivateVPN] Peer Connection Initiated with [AF_INET]45.130.87.14:1194
today at 10:49:02 PM2022-08-29 04:49:02 SENT CONTROL [PrivateVPN]: 'PUSH_REQUEST' (status=1)
today at 10:49:02 PM2022-08-29 04:49:02 PUSH: Received control message: 'PUSH_REPLY,explicit-exit-notify 2,comp-lzo no,sndbuf 524288,rcvbuf 524288,redirect-gateway def1,dhcp-option DISABLE-NBT,dhcp-option DNS 10.35.53.1,dhcp-option DNS 10.35.53.2,route-gateway 10.35.14.1,topology subnet,ping 20,ping-restart 60,ifconfig 10.35.14.152 255.255.254.0,peer-id 154,cipher AES-256-GCM'
today at 10:49:02 PM2022-08-29 04:49:02 Pushed option removed by filter: 'ping 20'
today at 10:49:02 PM2022-08-29 04:49:02 Pushed option removed by filter: 'ping-restart 60'
today at 10:49:02 PM2022-08-29 04:49:02 OPTIONS IMPORT: explicit notify parm(s) modified
today at 10:49:02 PM2022-08-29 04:49:02 OPTIONS IMPORT: compression parms modified
today at 10:49:02 PM2022-08-29 04:49:02 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
today at 10:49:02 PM2022-08-29 04:49:02 Socket Buffers: R=[212992->1048576] S=[212992->1048576]
today at 10:49:02 PM2022-08-29 04:49:02 OPTIONS IMPORT: --ifconfig/up options modified
today at 10:49:02 PM2022-08-29 04:49:02 OPTIONS IMPORT: route options modified
today at 10:49:02 PM2022-08-29 04:49:02 OPTIONS IMPORT: route-related options modified
today at 10:49:02 PM2022-08-29 04:49:02 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
today at 10:49:02 PM2022-08-29 04:49:02 OPTIONS IMPORT: peer-id set
today at 10:49:02 PM2022-08-29 04:49:02 OPTIONS IMPORT: adjusting link_mtu to 1625
today at 10:49:02 PM2022-08-29 04:49:02 OPTIONS IMPORT: data channel crypto options modified
today at 10:49:02 PM2022-08-29 04:49:02 Data Channel: using negotiated cipher 'AES-256-GCM'
today at 10:49:02 PM2022-08-29 04:49:02 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
today at 10:49:02 PM2022-08-29 04:49:02 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
today at 10:49:02 PM2022-08-29 04:49:02 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
today at 10:49:02 PM2022-08-29 04:49:02 TUN/TAP device tun0 opened
today at 10:49:02 PM2022-08-29 04:49:02 /sbin/ip link set dev tun0 up mtu 1500
today at 10:49:02 PM2022-08-29 04:49:02 /sbin/ip link set dev tun0 up
today at 10:49:02 PM2022-08-29 04:49:02 /sbin/ip addr add dev tun0 10.35.14.152/23
today at 10:49:02 PM2022-08-29 04:49:02 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.35.14.152 255.255.254.0 init
today at 10:49:02 PMUp script executed with tun0 1500 1553 10.35.14.152 255.255.254.0 init
today at 10:49:02 PMUpdating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.35.14.152
today at 10:49:02 PMUsing Combustion UI, overriding TRANSMISSION_WEB_HOME
today at 10:49:02 PMUpdating Transmission settings.json with values from env variables
today at 10:49:02 PMGenerating settings.json for Transmission from environment and defaults /etc/transmission/default-settings.json
today at 10:49:02 PMOverriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.35.14.152
today at 10:49:02 PMOverriding cache-size-mb because TRANSMISSION_CACHE_SIZE_MB is set to 10
today at 10:49:02 PMOverriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/downloads/complete
today at 10:49:02 PMOverriding download-queue-size because TRANSMISSION_DOWNLOAD_QUEUE_SIZE is set to 15
today at 10:49:02 PMOverriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/downloads/incomplete
today at 10:49:02 PMOverriding ratio-limit-enabled because TRANSMISSION_RATIO_LIMIT_ENABLED is set to true
today at 10:49:02 PMOverriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to true
today at 10:49:02 PMOverriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
today at 10:49:02 PMOverriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
today at 10:49:02 PMOverriding rpc-username because TRANSMISSION_RPC_USERNAME is set to redacted
today at 10:49:02 PMOverriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
today at 10:49:02 PMsed'ing True to true
today at 10:49:03 PMEnforcing ownership on transmission config directories
today at 10:49:03 PMApplying permissions to transmission config directories
today at 10:49:03 PM
today at 10:49:03 PM-------------------------------------
today at 10:49:03 PMTransmission will run as
today at 10:49:03 PM-------------------------------------
today at 10:49:03 PMUser name:   abc
today at 10:49:03 PMUser uid:    99
today at 10:49:03 PMUser gid:    100
today at 10:49:03 PM-------------------------------------
today at 10:49:03 PM
today at 10:49:03 PMSTARTING TRANSMISSION
today at 10:49:03 PMProvider PRIVATEVPN has a script for automatic port forwarding. Will run it now.
today at 10:49:03 PMIf you want to disable this, set environment variable DISABLE_PORT_UPDATER=true
today at 10:49:03 PMTransmission startup script complete.
today at 10:49:03 PM2022-08-29 04:49:03 /sbin/ip route add 45.130.87.14/32 via 172.17.0.1
today at 10:49:03 PM2022-08-29 04:49:03 /sbin/ip route add 0.0.0.0/1 via 10.35.14.1
today at 10:49:03 PM2022-08-29 04:49:03 /sbin/ip route add 128.0.0.0/1 via 10.35.14.1
today at 10:49:03 PM2022-08-29 04:49:03 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
today at 10:49:03 PM2022-08-29 04:49:03 Initialization Sequence Completed
today at 10:49:03 PMGot new port 61662 from PrivateVPN API
today at 10:49:03 PMtransmission auth required
today at 10:49:06 PMlocalhost:9091/transmission/rpc/ responded: "success"
today at 10:49:06 PMChecking port...
today at 10:49:17 PMPort is open: Yes

### HW/SW Environment

```markdown
- OS: Unraid 6.10.3
- Docker: 20.10.14
```

### Anything else?

The same thing was happening on an Asustor NAS. I figured it was the NAS screwing up. But now that it's followed to a new NAS runraid build I think its an issue with the docker.

**Comment by pkishino** [comment]
are you sure you have tested this with :dev branch ? I recall some restart stuff being sorted a while back..
also, if the openvpn tunnel looses connection, it depends on your config what it will do, default is to reestablish the connection. Then your other containers would need to re-establish connection as well if their connection didn't close successfully..

**Comment by ZerkerEOD** [comment]
I am not on the dev channel as I was getting errors the entire time and had no access to the panel and getting a TUN error. So I found this issue that explained dropping to 3.7.1 fixed it and it immediately fixed it for me. So now I am stuck on the 3.7.1 branch.

https://github.com/haugene/docker-transmission-openvpn/issues/2296

**Comment by ZerkerEOD** [comment]
Direct link to the resolution https://github.com/haugene/docker-transmission-openvpn/issues/2296#issuecomment-1221509150

**Comment by pkishino** [comment]
that fix is merged into dev

**Comment by ZerkerEOD** [comment]
Can confirm, I was able to update to the dev branch and my system is running. Thanks!

**Comment by ZerkerEOD** [comment]
@pkishino this issue is back and not fixed. If transmission loses the connection to the VPN for any reason I lose all access to every container behind it. I still have access to transmission once it comes back up but my connection to the other containers still never comes back even after an hour.
