### ISSUE TITLE
Connection Timed Out when removing torrents (and their data)

### ISSUE THREAD

**Issue by nwesthoff** [haugene/docker-transmission-openvpn#311]
**Description**

Disclaimer: I'm not sure if this is a problem with Transmission itself or your container. 
If I try to delete a torrent and its data (using transmission remote gui), it loses connection and I have to restart the container before being able to connect again. Sometimes it has actually removed the file, but not always.

**Steps to reproduce the issue:**
1. Open in transmission remote gui or web interface
2. Select a torrent to remove (including data)
3. Results in Remote GUI to stop responding
4. ![image](https://user-images.githubusercontent.com/7780722/30810431-69d8e902-a205-11e7-8b5f-955faa5ab65e.png)

**Describe the results you received:**
I've gotten each of these 3 outcomes (second happens most often):

1. Transmission works and I can remove the next torrent
2. Transmission doesn't allow me to connect, but has removed the torrent(s)
3. Transmission doesn't allow me to connect, and has not removed the torrent(s)

**Describe the results you expected:**
Transmission works and I can remove the next torrent

**Additional information you deem important (e.g. issue happens only occasionally):**
Transmission can't port forward consistently (works sometimes, but sometimes does not), happens either way.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 58
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 350
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-33-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.755GiB
Name: glados
ID: QTJ5:NZBD:WWUS:VTP7:3MWE:2ZHE:VK2L:TS3Z:5EYK:R3KO:CL4B:XS2X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Output of `docker logs transmission`**

```
STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Mon Sep 25 15:06:56 2017 Initialization Sequence Completed
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 56
Mon Sep 25 15:07:41 2017 event_wait : Interrupted system call (code=4)
Mon Sep 25 15:07:41 2017 /sbin/ip addr del dev tun0 local 10.85.10.6 peer 10.85.10.5
Mon Sep 25 15:07:41 2017 /etc/transmission/stop.sh tun0 1500 1558 10.85.10.6 10.85.10.5 init
Mon Sep 25 15:07:41 2017 SIGTERM[hard,] received, process exiting
Using OpenVPN provider: PIA
Starting OpenVPN using config Netherlands.ovpn
Setting OPENVPN credentials...
/etc/openvpn/start.sh: 45: /etc/openvpn/start.sh: dockerize: Resource temporarily unavailable
/etc/openvpn/start.sh: 70: /etc/openvpn/start.sh: /sbin/ip: Resource temporarily unavailable
Mon Sep 25 15:07:42 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Mon Sep 25 15:07:42 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Sep 25 15:07:42 2017 UDPv4 link local: [undef]
Mon Sep 25 15:07:42 2017 UDPv4 link remote: [AF_INET]109.201.154.184:1198
Mon Sep 25 15:07:42 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Sep 25 15:07:42 2017 [7a87c218868810e20dd8d97c3e63f3d8] Peer Connection Initiated with [AF_INET]109.201.154.184:1198
Mon Sep 25 15:07:44 2017 TUN/TAP device tun0 opened
Mon Sep 25 15:07:44 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Mon Sep 25 15:07:44 2017 /sbin/ip link set dev tun0 up mtu 1500
Mon Sep 25 15:07:44 2017 /sbin/ip addr add dev tun0 local 10.15.10.6 peer 10.15.10.5
Mon Sep 25 15:07:44 2017 /etc/transmission/start.sh tun0 1500 1558 10.15.10.6 10.15.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.15.10.6
Generating transmission settings.json from env variables
2017/09/25 15:07:44 Command finished successfully.
Setting owner for transmission paths to 1000:
/etc/transmission/start.sh: 10: [: Illegal number:

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1001
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Mon Sep 25 15:07:45 2017 Initialization Sequence Completed
Got new port 20061 from PIA
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Home server, running docker on Ubuntu 16.04 LTS. Error occurs when using local IP or nginx proxied URL.

**Comment by haugene** [comment]
Hmm, haven't seen this before. Thanks for providing all the information on this issue.
One thing I can't see though is what version of the image you're running? Is it the latest tag, or the dev tag maybe?

Before we do more digging, I just merged a bunch of changes to the master branch. So if you could try pulling the latest tag again (or release tag: 1.17) first and let me know if the problem is still there?

I also see that you get this error in your logs: `/etc/transmission/start.sh: 10: [: Illegal number:. See if that's still there in the new image as well. Could be related.
`

**Comment by nwesthoff** [comment]
Yep I'm running latest tag. I've just updated the container and I'm still getting disconnected.
```/etc/transmission/start.sh: 10: [: Illegal number``` still shows up in logs too.

**Comment by ErikHedblom** [comment]
I also had `/etc/transmission/start.sh: 10: [: Illegal number` showing up in my logs. Turns out I had passed `GUID` instead of `PGID` to the container. Fixing this removed this error message.

**Comment by nwesthoff** [comment]
Thanks @ErikHedblom, that did indeed remove the Illegal number error.
Didn't fix the problem unfortunately.

```
-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wed Nov  8 22:46:55 2017 Initialization Sequence Completed
Generating new client id for PIA
Got new port 35438 from PIA
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes
Wed Nov  8 22:47:21 2017 event_wait : Interrupted system call (code=4)
Wed Nov  8 22:47:21 2017 /sbin/ip addr del dev tun0 local 10.31.10.6 peer 10.31.10.5
Wed Nov  8 22:47:21 2017 /etc/transmission/stop.sh tun0 1500 1558 10.31.10.6 10.31.10.5 init
Wed Nov  8 22:47:21 2017 SIGTERM[hard,] received, process exiting
Using OpenVPN provider: PIA
Starting OpenVPN using config Netherlands.ovpn
Setting OPENVPN credentials...
2017/11/08 22:47:37 Command finished successfully.
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0
Wed Nov  8 22:47:37 2017 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Wed Nov  8 22:47:37 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Wed Nov  8 22:47:37 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Nov  8 22:47:38 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]185.107.44.31:1198
Wed Nov  8 22:47:38 2017 UDP link local: (not bound)
Wed Nov  8 22:47:38 2017 UDP link remote: [AF_INET]185.107.44.31:1198
Wed Nov  8 22:47:38 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Nov  8 22:47:38 2017 [62b1fa47326a24dd36e0b5dc391d958b] Peer Connection Initiated with [AF_INET]185.107.44.31:1198
Wed Nov  8 22:47:39 2017 TUN/TAP device tun0 opened
Wed Nov  8 22:47:39 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Wed Nov  8 22:47:39 2017 /sbin/ip link set dev tun0 up mtu 1500
Wed Nov  8 22:47:39 2017 /sbin/ip addr add dev tun0 local 10.6.10.6 peer 10.6.10.5
Wed Nov  8 22:47:39 2017 /etc/transmission/start.sh tun0 1500 1558 10.6.10.6 10.6.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.6.10.6
Generating transmission settings.json from env variables
2017/11/08 22:47:39 Command finished successfully.
Setting owner for transmission paths to 1000:1000

STARTING TRANSMISSION                                                                                                                                        
CONFIGURING PORT FORWARDING                                                                                                                                  
Transmission startup script complete.                                                                                                                        
Wed Nov  8 22:47:39 2017 Initialization Sequence Completed                                                                                                   
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding                 
curl encountered an error looking up new port: 56                                                                                                            
Wed Nov  8 22:49:53 2017 event_wait : Interrupted system call (code=4)                                                                                       
Wed Nov  8 22:49:53 2017 /sbin/ip addr del dev tun0 local 10.6.10.6 peer 10.6.10.5                                                                           
Wed Nov  8 22:49:53 2017 /etc/transmission/stop.sh tun0 1500 1558 10.6.10.6 10.6.10.5 init                                                                   
Wed Nov  8 22:49:53 2017 SIGTERM[hard,] received, process exiting                                                                                            
Using OpenVPN provider: PIA                                                                                                                                  
Starting OpenVPN using config Netherlands.ovpn                                                                                                               
Setting OPENVPN credentials...                                                                                                                               
2017/11/08 22:49:55 Command finished successfully.                                                                                                           
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0                                                                                         
Wed Nov  8 22:49:55 2017 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017             
Wed Nov  8 22:49:55 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08                                                                              
Wed Nov  8 22:49:55 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts                               
Wed Nov  8 22:49:55 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]46.166.188.209:1198                                                      
Wed Nov  8 22:49:55 2017 UDP link local: (not bound)                                                                                                         
Wed Nov  8 22:49:55 2017 UDP link remote: [AF_INET]46.166.188.209:1198                                                                                       
Wed Nov  8 22:49:55 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this                            
Wed Nov  8 22:49:55 2017 [5835f8b1ec9fd01ec93fd82eb2200e03] Peer Connection Initiated with [AF_INET]46.166.188.209:1198                                      
Wed Nov  8 22:49:56 2017 TUN/TAP device tun0 opened                                                                                                          
Wed Nov  8 22:49:56 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0                                                                                          
Wed Nov  8 22:49:56 2017 /sbin/ip link set dev tun0 up mtu 1500                                                                                              
Wed Nov  8 22:49:56 2017 /sbin/ip addr add dev tun0 local 10.29.10.6 peer 10.29.10.5                                                                         
Wed Nov  8 22:49:56 2017 /etc/transmission/start.sh tun0 1500 1558 10.29.10.6 10.29.10.5 init                                                                
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.29.10.6                                                                                       
Generating transmission settings.json from env variables                                                                                                     
2017/11/08 22:49:56 Command finished successfully.                                                                                                           
Setting owner for transmission paths to 1000:1000                                                                                                            
                                                                                                                                                             
-------------------------------------                                                                                                                        
Transmission will run as                                                                                                                                     
-------------------------------------                                                                                                                        
User name:   abc                                                                                                                                             
User uid:    1000                                                                                                                                            
User gid:    1000                                                                                                                                            
-------------------------------------                                                                                                                        
                                                                                                                                                             
STARTING TRANSMISSION                                                                                                                                        
CONFIGURING PORT FORWARDING                                                                                                                                  
Transmission startup script complete.                                                                                                                        
Wed Nov  8 22:49:56 2017 Initialization Sequence Completed                                                                                                   
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding                 
curl encountered an error looking up new port: 56                                                                                                            
```

Is the username supposed to be abc (that's not my actual username for uid/gid 1000)?
PIA does sometimes retrieve a new port, but it's not consistent, not sure if that could have something to do with my problems either.

**Comment by ErikHedblom** [comment]
Yes, the user should be `abc` inside the container. As long as the `uid` and `gid` are correct it will look like the correct user and group from outside the container. If the permissions are set correctly on the download folder I don't think this is a permissions problem. I also think more people would experience this in that case.

**Comment by haugene** [comment]
Closing this. Feel free to re-open if it's still a problem
