### ISSUE TITLE
NordVPN connection issues

### ISSUE THREAD

**Issue by pinionking** [haugene/docker-transmission-openvpn#932]
**Describe the problem**
Just started after update to the latest version. It is stuck in an endless connecting loop and won't connect to the VPN and start Transmission.

Just just repeats the same log entry below, with the exception of choosing a different server.

Has been running without a hitch until the latest update.

**Logs**
2019-10-24 22:26:12 Checking line endings,
2019-10-24 22:26:12 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config *******.nordvpn.com.tcp.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.0.0/16 via 172.17.0.1 dev eth0,
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/*****.nordvpn.com.tcp.ovpn:1: html (2.4.7),
Use --help for more information.,
Using OpenVPN provider: NORDVPN,
2019-10-24 22:27:30 Checking curl installation,
2019-10-24 22:27:30 Removing existing configs,
2019-10-24 22:27:30 Selecting the best server...,
2019-10-24 22:27:30 Searching for group: legacy_p2p,
2019-10-24 22:27:30 Searching for technology: openvpn_tcp,
2019-10-24 22:27:30 Best server : *****.nordvpn.com,
2019-10-24 22:27:30 Downloading config: default.ovpn,
2019-10-24 22:27:30 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/*****.nordvpn.com.tcp.tcp443.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
100   162  100   162    0     0     15      0  0:00:10  0:00:10 --:--:--    39,

**Host system:**
Ubuntu 19.04
Docker 18.09.7

**Comment by Sp33dFr34k** [comment]
Exactly the same for me, also a Nordvpn user.

**Comment by haugene** [comment]
Yes, seeing it here as well...

The download urls are like this:
`https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/no72.nordvpn.com.udp.udp1194.ovpn`

instead of:
`https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/no72.nordvpn.com.udp1194.ovpn`

**Comment by Steiniche** [comment]
The issue is that Nordvpn has moved their configs from `https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/xx123.nordvpn.com.udp.ovpn` to `https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/xx123.nordvpn.com.udp.ovpn` without doing a proper redirect.

**Comment by Steiniche** [comment]
@haugene you were 10 secs faster than me!
The affected line seems to be: https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/nordvpn/updateConfigs.sh#L87
Do you want a pull request or do you have time for fixing it?

**Comment by haugene** [comment]
Merge to master went too quick here. We already have two proposed solutions to the script:
https://github.com/haugene/docker-transmission-openvpn/pull/891
https://github.com/haugene/docker-transmission-openvpn/pull/899

I only need help determining which to merge I guess :)

**Comment by haugene** [comment]
Looking at it now, it looks like #899 might be a winner?
Or are they fixing different scenarios? One with default and the other with a specific ovpn file?

I'm on a bus on my way to a dinner. Can't dig into this right now 😆
But if you decide in this thread on the preferred action, then I can click merge on demand...

**Comment by Steiniche** [comment]
I would suggest #899 as it is the smallest change and it will fix the problem people are having now.

**Comment by Sp33dFr34k** [comment]
I agree :)

**Comment by haugene** [comment]
Done. Building now :)

**Comment by Sp33dFr34k** [comment]
Pulled the latest as soon as it was done building, but it seems it didn't fix it for me, keeps crashing and restarting the container.


2019-10-24 18:46:05 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/be94.nordvpn.com.udp.udp1194.ovpn | stdout
-- | --

Does it need the ovpn_udp dir now instead of ovpn_legacy?

**Comment by Cablethief** [comment]
I believe you also need to remove the .udp1194 from the end. So the end is like this:
https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/xx123.nordvpn.com.udp.ovpn

**Comment by Steiniche** [comment]
@Sp33dFr34k @Cabletheif
The need is to remove `.udp` in the middle of the string after `.com` and before `.udp1194.ovpn`

**Comment by Steiniche** [comment]
I have just tested with the changes from #899 and it does not seem to fix the problem.
There is still added an `.udp` to the download string.

**Comment by Sp33dFr34k** [comment]
Ah yes, did you test it on your setup @Steiniche?

**Comment by Steiniche** [comment]
Scratch my last comment, the fix from #899 works. 
If you do not have `OPENVPN_CONFIG` set the container will download a default configuration as expected.
The change from #899 has some side effects to how the `OPENVPN_CONFIG` option need to look.
Before you could have `xx123.nordvpn.com.udp` and it would work but with this change you will need `xx123.nordvpn.com.udp1194.ovpn`

**Comment by Sp33dFr34k** [comment]
Good spot, you're right... I just moved away from OPENVPN_CONFIG to the NORDVPN variables. So now it does seem to pick it up, but it's giving me a AUTH: Received control message: AUTH_FAILED error instead.

**Comment by Ueland** [comment]
Im not quite sure that it is all fixed just yet?
Just pulled again, still see the HTML issue mentioned here

```2019-10-24 20:20:14 Checking line endings
2019-10-24 20:20:14 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config no81.nordvpn.com.udp.ovpn
Setting OPENVPN credentials...
adding route to local network xxxxx dev eth0
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/no81.nordvpn.com.udp.ovpn:1: html (2.4.7)
Use --help for more information.```

**Comment by ToXinE** [comment]
Using OpenVPN provider: NORDVPN
2019-10-24 20:15:56 Checking curl installation
2019-10-24 20:15:56 Removing existing configs
2019-10-24 20:15:56 Selecting the best server...
2019-10-24 20:15:56 Searching for group: legacy_p2p
2019-10-24 20:15:56 Searching for technology: openvpn_udp
2019-10-24 20:15:56 Best server : XXXXyyyy.nordvpn.com
2019-10-24 20:15:56 Downloading config: default.ovpn
2019-10-24 20:15:56 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/XXXXyyyy.nordvpn.com.udp1194.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2809  100  2809    0     0  10715      0 --:--:-- --:--:-- --:--:-- 10721
2019-10-24 20:15:56 Selecting the best server...
2019-10-24 20:15:56 Searching for country : XXXX
2019-10-24 20:15:56 Searching for group: legacy_p2p
2019-10-24 20:15:56 Searching for technology: openvpn_udp
2019-10-24 20:15:56 Best server : XXXXyyyy.nordvpn.com
2019-10-24 20:15:56 Downloading config: XXXXyyyy.nordvpn.com.udp.ovpn
2019-10-24 20:15:56 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/XXXXyyyy.nordvpn.com.udp.udp1194.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    770      0 --:--:-- --:--:-- --:--:--   771
2019-10-24 20:15:56 Checking line endings
2019-10-24 20:15:56 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config XXXXyyyy.nordvpn.com.udp.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/16 via xxx.xxx.xxx.xxx dev eth0
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/XXXXyyyy.nordvpn.com.udp.ovpn:1: html (2.4.7)
Use --help for more information.

**Comment by Sp33dFr34k** [comment]
It looks like the both of you haven't set the OPENVPN_CONFIG as mentioned in @Steiniche 's comment?

**Comment by haugene** [comment]
Please post your settings so it's possible to reproduce. What openvpn
config and nordvpn environment variables are you using?

**Comment by ToXinE** [comment]
```
sudo docker run --cap-add=NET_ADMIN -d \
-e PUID=1003
-v /media/NAS/video/complete/movies/:/data \
-v /etc/localtime:/etc/localtime:ro \
-e CREATE_TUN_DEVICE=true \
-e OPENVPN_PROVIDER=NORDVPN \
-e OPENVPN_USERNAME=email@email.email \
-e OPENVPN_PASSWORD=XXXXXXXXXXXXXXXXXXXX \
-e NORDVPN_COUNTRY=YYY \
-e NORDVPN_PROTOCOL=udp \
-e NORDVPN_CATEGORY=P2P \
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
-e WEBPROXY_ENABLED=false \
-e LOCAL_NETWORK=192.168.0.0/16 \
--log-driver json-file \
--log-opt max-size=10m \
--restart=always \
-p 9091:9091 \
haugene/transmission-openvpn	
```

**Comment by Sp33dFr34k** [comment]
@ToXinE Just like I said, no OPENVPN_CONFIG variable, please read the above again and use it, then the latest build will work :)

**Comment by Ueland** [comment]
If OPENVPN_CONFIG has become required, then i suggest updating https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/ or some other pages to reflect that change :) 

Ps, the comments above is not crystal clear on what OPENVPN_CONFIG actually needs to be set to.

**Comment by Sp33dFr34k** [comment]
1. I agree with you, but seeing as we kinda pushed this merge on the creator @haugene it's not 100% yet. That's why I apologised in one of my previous posts.

2. I don't agree, it states clearly what needs to be set in @Steiniche 's post above, quote: "Before you could have xx123.nordvpn.com.udp and it would work but with this change you will need xx123.nordvpn.com.udp1194.ovpn"

3. I can imagine @haugene will push a proper merge later when he has more time, so that the nordvpn variables can be used again as well :)

**Comment by macross5** [comment]
@Sp33dFr34k why you can't post your docker run file as a example?
How I can change the url to xx123.nordvpn.com.udp1194.ovpn with env?

My config is like @ToXinE

**Comment by Sp33dFr34k** [comment]
@macross5 add this to your run file:

-e OPENVPN_CONFIG=xx123.nordvpn.com.udp1194.ovpn \

Obviously change the xx123 to whatever suits you best.

**Comment by koenvanderlinden** [comment]
I really don't like the OPENVPN_CONFIG changes as a perminant solution. I'm pushing a PR that works for me. Tested both with UDP and TCP.

**Comment by MajorLOL** [comment]
> @macross5 add this to your run file:
> 
> -e OPENVPN_CONFIG=xx123.nordvpn.com.udp1194.ovpn \
> 
> Obviously change the xx123 to whatever suits you best.

This fixed the issue for me.

**Comment by reaxi0n** [comment]
Yes but the point of using the Nord API is to get a server automatically. Out so I thought. Am I wrong in that assumption?

Why should "OPENVPN_CONFIG" have to exist when assigning a server from the API? I do not have that variable set. In fact I have it completely omitted in my configuration. And I'm still getting:

`2019-10-24 19:06:55 Checking line endings
2019-10-24 19:06:55 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config us4275.nordvpn.com.tcp.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 192.168.1.1 dev enp3s0
RTNETLINK answers: File exists
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/us4275.nordvpn.com.tcp.ovpn:1: html (2.4.7)
Use --help for more information.`

Over and over.

**Comment by andsoitgoes** [comment]
Thanks to you all for trying to figure this out, I thought I was going crazy. 

You guys rock, thank you for all your help!

**Comment by haugene** [comment]
Hey guys and thanks for being quick to point out and help fix this issue.
I've now merged the PR from @koenvanderlinden and a new build should be out soon.

I'll try to sit down with this a bit later today. I agree with many comments here about OPENVPN_CONFIG not supposed to be mandatory, and that we need to update the docs.

Just to confirm what we're aiming for. We have the NORDVPN_* environment variables and they should all be well documentet and also set with working default values.
When not setting OPENVPN_CONFIG - the recommended server from the API will be used.
When setting OPENVPN_CONFIG explicitly we will try to fetch that server and use it - and fail if it can't be retreived?

We still want to keep the possibility of choosing a specific server? Or should we just ignore OPENVPN_CONFIG for NordVPN and just print a message saying that you can choose category, protocol and country?

I have wanted to do a rewrite of some of the startup scripts for a while. Separate the provider specific from the core functionality. start.sh is always growing, time to split it up a bit.

**Comment by Sp33dFr34k** [comment]
Thanks for merging Koen's fix, it now works again with just the NORDVPN_* variables.

Personally for me it doesn't matter whether I can set a specific one or just let the software pick one based on the NORDVPN variables, but perhaps there is such a use case that one would want to set a specific one. So maybe just keep it as is and document the variables properly so it's clear for everyone :)

**Comment by Sirquen** [comment]
Hello everyone
i've setup OPENVPN_PROVIDER but no luck either...Anyone have an idea ?
Many thanks...

,Using OpenVPN provider: NORDVPN
,Setting NORDVPN_PROTOCOL to: UDP1194
,2019-10-25 17:06:37 Checking curl installation
,2019-10-25 17:06:37 Removing existing configs
,2019-10-25 17:06:37 Selecting the best server...
,2019-10-25 17:06:37 Searching for group: legacy_p2p
,2019-10-25 17:06:37 Searching for technology: openvpn_udp
,2019-10-25 17:06:37 Best server : xxx.nordvpn.com
,2019-10-25 17:06:37 Downloading config: default.ovpn
,2019-10-25 17:06:37 Downloading from: https://downloads.nordcdn.com/configs/filesfrxxx.nordvpn.com.ovpn
,  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
,                                 Dload  Upload   Total   Spent    Left  Speed
,
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    267      0 --:--:-- --:--:-- --:--:--   267
,2019-10-25 17:06:37 Using OpenVPN CONFIG :: xxx.nordvpn.com.udp1194
,2019-10-25 17:06:37 Downloading config: xxx.nordvpn.com.udp1194.ovpn
,2019-10-25 17:06:37 Downloading from: https://downloads.nordcdn.com/configs/filesfrxxx.nordvpn.com.udp1194.ovpn
,  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
,                                 Dload  Upload   Total   Spent    Left  Speed
,
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  5   162    5     9    0     0     14      0  0:00:11 --:--:--  0:00:11    14
100   162  100   162    0     0    260      0 --:--:-- --:--:-- --:--:--   260
,2019-10-25 17:06:37 Checking line endings
,2019-10-25 17:06:37 Updating configs for docker-transmission-openvpn
,Starting OpenVPN using config xxx.nordvpn.com.udp1194.ovpn
,Setting OPENVPN credentials...
,adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
,Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/xxx.nordvpn.com.udp1194.ovpn:1: html (2.4.7)
,Use --help for more information.
,`
,

**Comment by koenvanderlinden** [comment]
@Sirquen what env settings do you use for OPENVPN_CONFIG and what env settings for NORDVPN?
Could you try without any of those settings?

**Comment by Sirquen** [comment]
@koenvanderlinden Thank you !
Here are my env servings (global)

**OPENVPN_CONFIG** | XXX.nordvpn.com.udp1194 
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OPENVPN_USERNAME | XXX
OPENVPN_PASSWORD | XXX
**OPENVPN_PROVIDER** | NORDVPN
GLOBAL_APPLY_PERMISSIONS | true
TRANSMISSION_ALT_SPEED_DOWN | 50
TRANSMISSION_ALT_SPEED_ENABLED | false
TRANSMISSION_ALT_SPEED_TIME_BEGIN | 540
TRANSMISSION_ALT_SPEED_TIME_DAY | 127
TRANSMISSION_ALT_SPEED_TIME_ENABLED | false
TRANSMISSION_ALT_SPEED_TIME_END | 1020
TRANSMISSION_ALT_SPEED_UP | 50
TRANSMISSION_BIND_ADDRESS_IPV4 | 0.0.0.0
TRANSMISSION_BIND_ADDRESS_IPV6 | ::
TRANSMISSION_BLOCKLIST_ENABLED | false
TRANSMISSION_BLOCKLIST_URL | http://www.example.com/blocklist
TRANSMISSION_CACHE_SIZE_MB | 4
TRANSMISSION_DHT_ENABLED | true
TRANSMISSION_DOWNLOAD_DIR | /data/completed
TRANSMISSION_DOWNLOAD_LIMIT | 100
TRANSMISSION_DOWNLOAD_LIMIT_ENABLED | 0
TRANSMISSION_DOWNLOAD_QUEUE_ENABLED | true
TRANSMISSION_DOWNLOAD_QUEUE_SIZE | 5
TRANSMISSION_ENCRYPTION | 1
TRANSMISSION_IDLE_SEEDING_LIMIT | 30
TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED | false
TRANSMISSION_INCOMPLETE_DIR | /data/incomplete
TRANSMISSION_INCOMPLETE_DIR_ENABLED | true
TRANSMISSION_LPD_ENABLED | false
TRANSMISSION_MAX_PEERS_GLOBAL | 200
TRANSMISSION_MESSAGE_LEVEL | 2
TRANSMISSION_PEER_CONGESTION_ALGORITHM |  
TRANSMISSION_PEER_ID_TTL_HOURS | 6
TRANSMISSION_PEER_LIMIT_GLOBAL | 200
TRANSMISSION_PEER_LIMIT_PER_TORRENT | 50
TRANSMISSION_PEER_PORT | 51413
TRANSMISSION_PEER_PORT_RANDOM_HIGH | 65535
TRANSMISSION_PEER_PORT_RANDOM_LOW | 49152
TRANSMISSION_PEER_PORT_RANDOM_ON_START | false
TRANSMISSION_PEER_SOCKET_TOS | default
TRANSMISSION_PEX_ENABLED | true
TRANSMISSION_PORT_FORWARDING_ENABLED | false
TRANSMISSION_PREALLOCATION | 1
TRANSMISSION_PREFETCH_ENABLED | 1
TRANSMISSION_QUEUE_STALLED_ENABLED | true
TRANSMISSION_QUEUE_STALLED_MINUTES | 30
TRANSMISSION_RATIO_LIMIT | 2
TRANSMISSION_RATIO_LIMIT_ENABLED | false
TRANSMISSION_RENAME_PARTIAL_FILES | true
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED | false
TRANSMISSION_RPC_BIND_ADDRESS | 0.0.0.0
TRANSMISSION_RPC_ENABLED | true
TRANSMISSION_RPC_HOST_WHITELIST |  
TRANSMISSION_RPC_HOST_WHITELIST_ENABLED | false
TRANSMISSION_RPC_PASSWORD | password
TRANSMISSION_RPC_PORT | 9091
TRANSMISSION_RPC_URL | /transmission/
TRANSMISSION_RPC_USERNAME | username
TRANSMISSION_RPC_WHITELIST | 127.0.0.1
TRANSMISSION_RPC_WHITELIST_ENABLED | false
TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED | true
TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED | false
TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME |  
TRANSMISSION_SEED_QUEUE_ENABLED | false
TRANSMISSION_SEED_QUEUE_SIZE | 10
TRANSMISSION_SPEED_LIMIT_DOWN | 100
TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED | false
TRANSMISSION_SPEED_LIMIT_UP | 100
TRANSMISSION_SPEED_LIMIT_UP_ENABLED | false
TRANSMISSION_START_ADDED_TORRENTS | true
TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES | false
TRANSMISSION_UMASK | 2
TRANSMISSION_UPLOAD_LIMIT | 100
TRANSMISSION_UPLOAD_LIMIT_ENABLED | 0
TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT | 14
TRANSMISSION_UTP_ENABLED | true
TRANSMISSION_WATCH_DIR | /data/watch
TRANSMISSION_WATCH_DIR_ENABLED | true
TRANSMISSION_HOME | /data/transmission-home
TRANSMISSION_WATCH_DIR_FORCE_GENERIC | false
ENABLE_UFW | false
UFW_ALLOW_GW_NET | false
UFW_EXTRA_PORTS |  
UFW_DISABLE_IPTABLES_REJECT | false
TRANSMISSION_WEB_UI | combustion
PUID | 1026
PGID | 100
TRANSMISSION_WEB_HOME |  
DROP_DEFAULT_ROUTE |  
WEBPROXY_ENABLED | false
WEBPROXY_PORT | 8888
HEALTH_CHECK_HOST | google.com
LOCAL_NETWORK | 192.168.1.0/24

**Comment by Sirquen** [comment]
@koenvanderlinden Do you have an idea ? :)

**Comment by progtologist** [comment]
Looks like NORDVPN changed their API again.
The new image does not work for me anymore because:
```bash
curl -s "https://api.nordvpn.com/v1/servers/recommendations?limit=1" | jq --raw-output ".[].hostname"
```
now returns
```
xx123.nordvpn.com
```
instead of the expected URL `xx123.nordvpn.com.udp`

Therefore we need to change the
```bash
nordvpn_cdn="${nordvpn_cdn}.ovpn"
```
to
```bash
if [[ ${NORDVPN_PROTOCOL,,} == udp ]]; then
    nordvpn_cdn="${nordvpn_cdn}.udp.ovpn"
elif [[ ${NORDVPN_PROTOCOL,,} == tcp ]];then
    nordvpn_cdn="${nordvpn_cdn}.tcp.ovpn"
fi
```
Can someone make a PR with the fix?

**Comment by haugene** [comment]
Let's hope it stabilises soon. Thanks for the proposed solution @progtologist, seems to work fine 👍

**Comment by pinionking** [comment]
It's come back again after the latest update.

**Comment by scottjl** [comment]
With all the stupid changes NordVPN keeps making, is there a simple way to just overlay my own config file into the image to be used? You can grab all the config files yourself with a simple `wget https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip`. Until they settle down, I'd just like to pick one out of the file, map it into the image, and go. It's a hack, but at least it would work.

**Comment by koenvanderlinden** [comment]
@Sirquen Try it without the OPENVPN_CONFIG | XXX.nordvpn.com.udp1194
The new docker image should work without this setting, so make it empty.

**Comment by andsoitgoes** [comment]
@koenvanderlinden 

So just remove that entire line for OpenVPN config?

**Comment by koenvanderlinden** [comment]
@andsoitgoes There are some NORDVPN_* environment variables that will control the search for vpn server. Check [https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/](url).

**Comment by tdegroef** [comment]
For me it worked for a brief moment yesterday but this morning I see this in my logs and it keeps repeating:

Using OpenVPN provider: NORDVPN
2019-10-26 10:23:46 Checking curl installation
2019-10-26 10:23:46 Removing existing configs
2019-10-26 10:23:46 Selecting the best server...
2019-10-26 10:23:46 Searching for group: legacy_p2p
2019-10-26 10:23:46 Searching for technology: openvpn_udp
2019-10-26 10:23:46 Best server : xx115.nordvpn.com
2019-10-26 10:23:46 Downloading config: default.ovpn
2019-10-26 10:23:46 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/xx115.nordvpn.com.udp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2809  100  2809    0     0   4076      0 --:--:-- --:--:-- --:--:--  4076
2019-10-26 10:23:46 Selecting the best server...
2019-10-26 10:23:46 Searching for country : xx (21)
2019-10-26 10:23:46 Searching for group: legacy_p2p
2019-10-26 10:23:46 Searching for technology: openvpn_udp
2019-10-26 10:23:46 Best server : xx115.nordvpn.com
2019-10-26 10:23:46 Downloading config: xx115.nordvpn.com.udp.ovpn
2019-10-26 10:23:46 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/xx115.nordvpn.com.udp.udp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    235      0 --:--:-- --:--:-- --:--:--   235
2019-10-26 10:23:46 Checking line endings
2019-10-26 10:23:46 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config xx115.nordvpn.com.udp.ovpn
Setting OPENVPN credentials...
adding route to local network xxx.xxx.x.x/24 via 172.18.0.1 dev eth0
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/xx115.nordvpn.com.udp.ovpn:1: html (2.4.7)
Use --help for more information.

and this is my config:
 - NORDVPN_COUNTRY=XX
 - NORDVPN_CATEGORY=P2P
 - OPENVPN_PROVIDER=NORDVPN
 - OPENVPN_USERNAME=xxxx@xxx.com
 - OPENVPN_PASSWORD=xxxx
 - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
 - LOCAL_NETWORK=xxx.xxx.x.x/24

Does someone have a idea?

**Comment by Sirquen** [comment]
@koenvanderlinden Thank you !
Pulling the latest image does the trick
@tdegroef Try to pull the latest :)

**Comment by Darathor17** [comment]
Confirm that it works now. Thank you all that help resolved the issue!

**Comment by koenvanderlinden** [comment]
@tdegroef Which version of branch do you use? The problem at your container it's trying to download https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/xx115.nordvpn.com.udp.udp.ovpn
Filename has duplicate .udp. in it.

I noticed a difference in master and dev how this is handles. Both branches have a different approach. This should be changed by doing a rebase or something. PR from dev are pulled into main and you get weird issues like this.

```
Master branch:
if [[ ! -z $OPENVPN_CONFIG ]] && [[ ! -z $NORDVPN_COUNTRY ]]
then
    default="$(select_hostname)"
else
    default="$(select_hostname -d)"
fi
download_hostname -d ${default}

dev branch:
if [[ ! -z $OPENVPN_CONFIG ]] && [[ ! -z $NORDVPN_COUNTRY ]]
then
    default="$(select_hostname)"
else
    default="$(select_hostname -d)"
fi
download_hostname -d ${default}
```

And when downloading:
```
master  branch:
if [[ ${NORDVPN_PROTOCOL,,} == udp ]]; then
        nordvpn_cdn="${nordvpn_cdn}.udp.ovpn"
    elif [[ ${NORDVPN_PROTOCOL,,} == tcp ]];then
        nordvpn_cdn="${nordvpn_cdn}.tcp.ovpn"
    fi

dev branch:
nordvpn_cdn="${nordvpn_cdn}.ovpn"
```

Master branch should work fine. Just tested it. I assume the latest image will be working to. Just confirmed by @Darathor17.

**Comment by tdegroef** [comment]
@Sirquen I'm already at the latest version

docker pull haugene/transmission-openvpn
Using default tag: latest
latest: Pulling from haugene/transmission-openvpn
Digest: sha256:b5f88e89172d3b81f5ebefd7289ce94589bfc8a8d0e3b303a6dce1c8166172c1
Status: Image is up to date for haugene/transmission-openvpn:latest
docker.io/haugene/transmission-openvpn:latest

@koenvanderlinden How do I check the exact branch I'm using?

**Comment by haugene** [comment]
> With all the stupid changes NordVPN keeps making, is there a simple way to just overlay my own config file into the image to be used? 

@scottjl Yes there is. This is described [here](https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_custom_provider). You just mount your configs at `/etc/openvpn/custom/` and then you can set OPENVPN_PROVIDER=custom and OPENVPN_CONFIG=yourfile

> I noticed a difference in master and dev how this is handles. Both branches have a different approach.

@koenvanderlinden Merged changes from master into dev now, so they're the same again.

> How do I check the exact branch I'm using?

@tdegroef The :latest tag is built from master, the :dev tag is built from dev branch. So you're on master. If it still doesn't work and you need it to (before we get this script right), try the custom-config approach outlined above.

**Comment by Darathor17** [comment]
If it helps, when using `OPENVPN_CONFIG` it works well. While when trying with `NORDVPN_COUNTRY` & `NORDVPN_CATEGORY=P2P` it fails (see logs below)

> Selecting the best server...
> Searching for country : FR (74)
> Searching for group: legacy_p2p
> Searching for technology: openvpn_udp
> Best server : fr380.nordvpn.com
> Downloading config: fr380.nordvpn.com.udp.ovpn
> Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/fr380.nordvpn.com.udp.udp.ovpn
>    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                   Dload  Upload   Total   Spent    Left  Speed
> 100   162  100   162    0     0    327      0 --:--:-- --:--:-- --:--:--   327
> Checking line endings
> Updating configs for docker-transmission-openvpn
> Starting OpenVPN using config fr380.nordvpn.com.udp.ovpn
> Setting OPENVPN credentials...
> adding route to local network 192.168.0.0/24 via 172.16.1.1 dev eth0
> Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/fr380.nordvpn.com.udp.ovpn:1: html (2.4.6)

**Comment by koenvanderlinden** [comment]
@Darathor17 I'll have a look at those NORDVPN_xxx params.

**Comment by tdegroef** [comment]
@koenvanderlinden I just updated to the latest version and it works again.

Thank you for solving this

**Comment by Darathor17** [comment]
strange and maybe unrelated but with latest build it's not working anymore (I tried with and without OPVN_CONFIG). To be noted I use latest:alpine image (I'll test on the latest ASAP)

>  Using OpenVPN provider: NORDVPN
>  2019-10-26 13:03:22 Checking curl installation
>  2019-10-26 13:03:22 Removing existing configs
>  2019-10-26 13:03:22 Selecting the best server...
>  parse error: Invalid numeric literal at EOF at line 1, column 4
>  2019-10-26 13:03:22 Searching for technology: openvpn_udp
>  parse error: Invalid numeric literal at EOF at line 1, column 4
>  2019-10-26 13:03:22 Unable to find a server with the specified parameters, using any recommended server
>  parse error: Invalid numeric literal at EOF at line 1, column 4
>  2019-10-26 13:03:22 Best server :
>  2019-10-26 13:03:22 Downloading config: default.ovpn
>  2019-10-26 13:03:22 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn
>    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                   Dload  Upload   Total   Spent    Left  Speed
> 100   162  100   162    0     0    593      0 --:--:-- --:--:-- --:--:--   593
>  2019-10-26 13:03:22 Selecting the best server...
>  parse error: Invalid numeric literal at EOF at line 1, column 4
>  parse error: Invalid numeric literal at EOF at line 1, column 4
>  2019-10-26 13:03:22 Searching for technology: openvpn_udp
>  parse error: Invalid numeric literal at EOF at line 1, column 4
>  2019-10-26 13:03:22 Unable to find a server with the specified parameters, using any recommended server
>  parse error: Invalid numeric literal at EOF at line 1, column 4
>  2019-10-26 13:03:22 Best server :
>  2019-10-26 13:03:22 Downloading config: .ovpn
>  2019-10-26 13:03:22 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn
>    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                   Dload  Upload   Total   Spent    Left  Speed
> 100   162  100   162    0     0    287      0 --:--:-- --:--:-- --:--:--   286
>  2019-10-26 13:03:22 Checking line endings
>  2019-10-26 13:03:22 Updating configs for docker-transmission-openvpn
>  No VPN configuration provided. Using default.
>  Setting OPENVPN credentials...
>  adding route to local network 192.168.0.0/24 via 172.16.1.1 dev eth0
>  Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.6)
>  Use --help for more information.

**Comment by koenvanderlinden** [comment]
I think this issue can be closed.

**Comment by Sp33dFr34k** [comment]
Mine is crashing again though, using the latest and nordvpn_* variables. The link shows udp twice again, unsure why. Checking on my phone so it's not ideal. Nobody else with this issue?

**Comment by koenvanderlinden** [comment]
@Sp33dFr34k can you show us the log's? And some of your ENV settings (NORDVPN_* and OPENVPN_CONFIG)?

**Comment by Sp33dFr34k** [comment]
@koenvanderlinden this line is the issue:

2019-10-26 19:13:47 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/be84.nordvpn.com.udp.udp.ovpn | stdout
-- | --

Using NORDVPN_COUNTRY=be and NORDVPN_PROTOCOL=udp variables, no OPENVPN_CONFIG.

**Comment by koenvanderlinden** [comment]
@Sp33dFr34k Did you pull the latest docker image? As this issue was fixed around 12:00. @Darathor17 had the same issue and that was fixed in the latest docker image.

As a fallback you could try it without the NORDVPN_ settings.
If that works and with NORDVPN_* settings it doesn't work, you were probably not using the latest image.

**Comment by Sp33dFr34k** [comment]
Okay, switched to laptop now. I am using dockupdater, so I assumed it pulled the latest, just pulled it manually now and it works so far. Totally my bad. Let's see how long it remains working this time, thanks Koen :)

So like you said, @haugene can close this issue as it's confirmed fixed now.

**Comment by koenvanderlinden** [comment]
@haugene Could you merge master into dev?
At this moment the dev branch will not download the non default (country specific) configs.
